version: "3.7"

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    networks:
      - jotihunt
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 20

  jotihunt:
    image: ghcr.io/scoutingijsselgroep/jotihunt:latest
    build:
      context: '.'
      target: 'development'
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOSTNAME}/${MYSQL_DATABASE}
    volumes:
      - './seeders/:/reactapp/seeders'
      - './server/:/reactapp/server'
      - './app/:/reactapp/app'
    networks:
      - jotihunt
    depends_on:
      db:
        condition: service_healthy
  # clairvoyance:
  #   image: ghcr.io/scoutingijsselgroep/jotihunt-clairvoyance:latest
  #   restart: always
  #   environment:
  #     - AUTH0_CLIENT_ID
  #     - AUTH0_DOMAIN
  #     - TELEGRAM_TOKEN
  #     - GOOGLE_SERVER_AUTH_TOKEN
  #     - GOOGLE_CLIENT_AUTH_TOKEN
  #     - KML_FILENAME
  #     - POLLER_INTERVAL_SECONDS
  #     - POLLER_API_KEY
  #   networks:
  #     - jotihunt
  #   labels:
  #     - traefik.enable = false
  # divinity:
  #   image: ghcr.io/scoutingijsselgroep/jotihunt-divinity:latest
  #   restart: always
  #   environment:
  #     - AUTH0_CLIENT_ID
  #     - AUTH0_DOMAIN
  #     - TELEGRAM_TOKEN
  #     - GOOGLE_SERVER_AUTH_TOKEN
  #     - GOOGLE_CLIENT_AUTH_TOKEN
  #     - KML_FILENAME
  #     - POLLER_INTERVAL_SECONDS
  #     - POLLER_API_KEY
  #   networks:
  #     - jotihunt
  #   labels:
  #     - traefik.enable = false
networks:
  jotihunt:
    name: jotihunt

volumes:
  dbdata:
