version: "3.7"

services:
  jotihunt:
    image: tristandb/jotihunt:latest
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOSTNAME}/${MYSQL_DATABASE}
    networks:
      - jotihunt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jotihunt.rule=Host(`jotihunt.scouting-ijsselgroep.nl`)"
      - "traefik.http.routers.jotihunt.entrypoints=websecure"
      - "traefik.http.services.jotihunt-service.loadbalancer.server.port=3000"
      - "traefik.http.routers.jotihunt.tls.certresolver=myresolver"
    depends_on:
      - "db"

  traefik:
    image: traefik:v2.5
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.swarmMode=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=${CLOUDFLARE_API_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    container_name: traefik
    environment:
      # Cloudflare Global API Key for Let's Encrypt
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_EMAIL}
      - C_COUNTER=1
    networks:
      - jotihunt

  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    networks:
      - jotihunt
    labels:
      - traefik.enable = false

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 20

networks:
  jotihunt:
    name: jotihunt

volumes:
  dbdata:
