services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8000:80
    networks:
      - jotihunt
    labels:
      - traefik.backend=phpmyadmin
      - traefik.frontend.rule=Host:phpmyadmin.scouting-ijsselgroep.nl
      - traefik.docker.network=proxy
      - traefik.port=80

networks:
  jotihunt:
    name: jotihunt
