version: "3.7"

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    networks:
      - jotihunt
    labels:
      - traefik.enable = false

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8000:80
    networks:
      - jotihunt
    labels:
      - traefik.backend=phpmyadmin
      - traefik.frontend.rule=Host:phpmyadmin.scouting-ijsselgroep.nl
      - traefik.docker.network=proxy
      - traefik.port=80
  jotihunt:
    image: ghcr.io/scoutingijsselgroep/jotihunt:latest
    build:
      context: '.'
      target: 'development'
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOSTNAME}/${MYSQL_DATABASE}
      - RUN_COUNTER
      - API_URI
      - PORT
      - AUTH0_CLIENT_ID
      - AUTH0_DOMAIN
      - TELEGRAM_TOKEN
      - GOOGLE_SERVER_AUTH_TOKEN
      - GOOGLE_CLIENT_AUTH_TOKEN
      - KML_FILENAME
      - POLLER_INTERVAL_SECONDS
      - POLLER_API_KEY
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - './seeders/:/reactapp/seeders'
      - './server/:/reactapp/server'
      - './app/:/reactapp/app'
    networks:
      - jotihunt
    labels:
      - traefik.backend=jotihunt
      - traefik.frontend.rule=Host:${HOST_URI}
      - traefik.docker.network=proxy
      - traefik.port=3000
    depends_on:
      db:
        condition: service_healthy
  clairvoyance:
    image: ghcr.io/scoutingijsselgroep/jotihunt-clairvoyance:latest
    restart: always
    environment:
      - AUTH0_CLIENT_ID
      - AUTH0_DOMAIN
      - TELEGRAM_TOKEN
      - GOOGLE_SERVER_AUTH_TOKEN
      - GOOGLE_CLIENT_AUTH_TOKEN
      - KML_FILENAME
      - POLLER_INTERVAL_SECONDS
      - POLLER_API_KEY
    networks:
      - jotihunt
    labels:
      - traefik.enable = false
  divinity:
    image: ghcr.io/scoutingijsselgroep/jotihunt-divinity:latest
    restart: always
    environment:
      - AUTH0_CLIENT_ID
      - AUTH0_DOMAIN
      - TELEGRAM_TOKEN
      - GOOGLE_SERVER_AUTH_TOKEN
      - GOOGLE_CLIENT_AUTH_TOKEN
      - KML_FILENAME
      - POLLER_INTERVAL_SECONDS
      - POLLER_API_KEY
    networks:
      - jotihunt
    labels:
      - traefik.enable = false
  traefik:
    image: traefik:1.7.18-alpine
    command: --api --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/traefik/traefik.toml:/traefik.toml
      - /var/traefik/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      - traefik.frontend.rule=Host:backend.scouting-ijsselgroep.nl
      - traefik.port=8080
    environment:
      - CF_API_EMAIL
      - CF_API_KEY
      - C_COUNTER
    networks:
      - jotihunt
networks:
  jotihunt:
    name: jotihunt

volumes:
  dbdata:
